# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd1e4efbcdc045a0384f750d0a55b72f4b482e948021f49d3af2b1e7ae97885522ec4408de79d2a7482aea3049423c9aaab3ba6a868e190c58876bc21025d75b

test:
  secret_key_base: cc178b7c66da6017e96c3b251b0dd0ba40ebfbabfd56506f6b4c254a376d19eb027a11020a39e2b27ea5712c4f96ca0b0a21c96215e8a3bc889b6a7522f74ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
